// <auto-generated />
using System;
using ChalkScore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChalkScore.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430005832_TestBuilder")]
    partial class TestBuilder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.Gymnast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Gymnasts");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.GymnastLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GymnastLevels");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TestTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestTypeId");

                    b.ToTable("TestConfigurations");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestConfigurationExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("ScoringParams")
                        .HasColumnType("text");

                    b.Property<int>("ScoringType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TestConfigurationId");

                    b.ToTable("TestConfigurationExercises");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RawValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TestSessionGymnastId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TestSessionGymnastId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestSessionGymnast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GymnastId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TestConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GymnastId");

                    b.HasIndex("TestConfigurationId");

                    b.HasIndex("TestSessionId");

                    b.ToTable("TestSessionGymnasts");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.Gymnast", b =>
                {
                    b.HasOne("ChalkScore.Api.Data.Entities.GymnastLevel", "Level")
                        .WithMany("Gymnasts")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestConfiguration", b =>
                {
                    b.HasOne("ChalkScore.Api.Data.Entities.TestType", "TestType")
                        .WithMany("Versions")
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestConfigurationExercise", b =>
                {
                    b.HasOne("ChalkScore.Api.Data.Entities.Exercise", "Exercise")
                        .WithMany("TestConfigurationExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChalkScore.Api.Data.Entities.TestConfiguration", "TestConfiguration")
                        .WithMany("Exercises")
                        .HasForeignKey("TestConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TestConfiguration");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestResult", b =>
                {
                    b.HasOne("ChalkScore.Api.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChalkScore.Api.Data.Entities.TestSessionGymnast", "TestSessionGymnast")
                        .WithMany("Results")
                        .HasForeignKey("TestSessionGymnastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TestSessionGymnast");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestSessionGymnast", b =>
                {
                    b.HasOne("ChalkScore.Api.Data.Entities.Gymnast", "Gymnast")
                        .WithMany("TestSessionGymnasts")
                        .HasForeignKey("GymnastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChalkScore.Api.Data.Entities.TestConfiguration", "TestConfiguration")
                        .WithMany()
                        .HasForeignKey("TestConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChalkScore.Api.Data.Entities.TestSession", "TestSession")
                        .WithMany("Gymnasts")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gymnast");

                    b.Navigation("TestConfiguration");

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.User", b =>
                {
                    b.HasOne("ChalkScore.Api.Data.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.Exercise", b =>
                {
                    b.Navigation("TestConfigurationExercises");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.Gymnast", b =>
                {
                    b.Navigation("TestSessionGymnasts");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.GymnastLevel", b =>
                {
                    b.Navigation("Gymnasts");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestConfiguration", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestSession", b =>
                {
                    b.Navigation("Gymnasts");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestSessionGymnast", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("ChalkScore.Api.Data.Entities.TestType", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
